# Generated by Django 4.0.1 on 2022-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('ECONOMY', 'ECONOMY'), ('BUSINESS', 'BUSINESS'), ('FIRST CLASS', 'FIRST CLASS')], max_length=256, verbose_name='Car category'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('ELECTRIC', 'ELECTRIC'), ('HYBRID', 'HYBRID'), ('INTERNAL COMBUSTION ENGINE', 'INTERNAL COMBUSTION ENGINE')], max_length=256, verbose_name='Engine type'),
        ),
    ]
